### ISSUE TITLE
Remote Workspace Configuration v3.1.5 doesn't work in RAD 9.1

### ISSUE THREAD

**Issue by andham** [netceteragroup/eclipse-team-etceteras#22]
I've installed Remote Workspace Configuration v3.1.5 in IBM RAD 9.1 (based on Eclipse 4.2.x) and it shows up as installed but it doesn't work. There configuration section in Preferences doesn't exist and there is not remote import option when selecting File->Import.
Can't find anything in the Eclipse workspace log file related to this.

**Comment by andham** [comment]
In RAD 9.5.0.1 I've successfully used Remote Workspace Configuration v3.1.5. Not sure if it was something I did wrong in RAD 9.1 or if it was a problem specific to RAD 9.1, but I think this ticket can be closed as it works in RAD 9.5.

**Comment by marschall** [comment]
Thanks for reporting back.
